---
- hosts: webservers
  tasks:

  - name: Install package nginx
    yum: name=nginx update_cache=yes
    sudo: yes

  - name: Starting service nginx
    service: name=nginx state=started
    sudo: yes
